### ISSUE TITLE
AO3 worm story not showing up

### ISSUE THREAD

**Issue by pokeball99** [griffithchaffee/wormstorysearch-rails#11]
https://archiveofourown.org/works/5683105/chapters/13092007
searching under "Guardian" and "Vulgarian" fail to show it, not really sure why it wouldn't show

**Comment by griffithchaffee** [comment]
The author rated the story as explicit so it is marked as NSFW. You can choose to include NSFW options in your search but by default they are excluded. You can find the story [here](https://wormstorysearch.com/?is_nsfw_eq=true&story_keywords=Guardian&searching=true).
