### ISSUE TITLE
DB Dump of past updates

### ISSUE THREAD

**Issue by thorncorona** [griffithchaffee/wormstorysearch-rails#16]
Is it possible to get a DB dump of WSS?

**Comment by griffithchaffee** [comment]
Hi @thorncorona 

Here is a direct download link with the latest story data (excludes session data for obvious reasons):
[wormstorysearch-2020-07-19](https://wormstorysearch.s3.amazonaws.com/dumps/wormstorysearch-2020-07-19.zip)

Assuming you are using PostgreSQL, you can import the SQL file contained within the zip using a command similar to:
`cat wormstorysearch-2019-07-19.sql | psql -U postgres -h localhost postgres`

**Comment by thorncorona** [comment]
Thanks!
