### ISSUE TITLE
Ratings for Spacebattles/SufficientVelocity not working

### ISSUE THREAD

**Issue by Xfel** [griffithchaffee/wormstorysearch-rails#18]
Looking at new stories, they all have a rating of 0, even though there are likes on the story itself. Only affects Spacebattles and SufficientVelocity, AO3 and FF.net are fine.

I see that the newest forum story that has a rating was created December 11th, the next forum story without a rating was created December 16th.

**Comment by griffithchaffee** [comment]
Fixed!
